gambit-enummixed -q nfgs/game0.nfg
gambit-enummixed -q nfgs/game1.nfg
gambit-enummixed -q nfgs/game2.nfg
gambit-enummixed -q nfgs/game3.nfg
gambit-enummixed -q nfgs/game4.nfg
gambit-enummixed -q nfgs/game5.nfg
gambit-enummixed -q nfgs/game6.nfg
gambit-enummixed -q nfgs/game7.nfg
gambit-enummixed -q nfgs/game8.nfg
gambit-enummixed -q nfgs/game9.nfg
gambit-enummixed -q nfgs/game10.nfg
gambit-enummixed -q nfgs/game11.nfg
gambit-enummixed -q nfgs/game12.nfg
gambit-enummixed -q nfgs/game13.nfg
gambit-enummixed -q nfgs/game14.nfg
gambit-enummixed -q nfgs/game15.nfg
gambit-enummixed -q nfgs/game16.nfg
gambit-enummixed -q nfgs/game17.nfg
gambit-enummixed -q nfgs/game18.nfg
gambit-enummixed -q nfgs/game19.nfg
gambit-enummixed -q nfgs/game20.nfg
gambit-enummixed -q nfgs/game21.nfg
gambit-enummixed -q nfgs/game22.nfg
gambit-enummixed -q nfgs/game23.nfg
gambit-enummixed -q nfgs/game24.nfg
gambit-enummixed -q nfgs/game25.nfg
gambit-enummixed -q nfgs/game26.nfg
gambit-enummixed -q nfgs/game27.nfg
gambit-enummixed -q nfgs/game28.nfg
gambit-enummixed -q nfgs/game29.nfg
gambit-enummixed -q nfgs/game30.nfg
gambit-enummixed -q nfgs/game31.nfg
gambit-enummixed -q nfgs/game32.nfg
gambit-enummixed -q nfgs/game33.nfg
gambit-enummixed -q nfgs/game34.nfg
gambit-enummixed -q nfgs/game35.nfg
gambit-enummixed -q nfgs/game36.nfg
gambit-enummixed -q nfgs/game37.nfg
gambit-enummixed -q nfgs/game38.nfg
gambit-enummixed -q nfgs/game39.nfg
gambit-enummixed -q nfgs/game40.nfg
gambit-enummixed -q nfgs/game41.nfg
gambit-enummixed -q nfgs/game42.nfg
gambit-enummixed -q nfgs/game43.nfg
gambit-enummixed -q nfgs/game44.nfg
gambit-enummixed -q nfgs/game45.nfg
gambit-enummixed -q nfgs/game46.nfg
gambit-enummixed -q nfgs/game47.nfg
gambit-enummixed -q nfgs/game48.nfg
gambit-enummixed -q nfgs/game49.nfg
gambit-enummixed -q nfgs/game50.nfg
gambit-enummixed -q nfgs/game51.nfg
gambit-enummixed -q nfgs/game52.nfg
gambit-enummixed -q nfgs/game53.nfg
gambit-enummixed -q nfgs/game54.nfg
gambit-enummixed -q nfgs/game55.nfg
gambit-enummixed -q nfgs/game56.nfg
gambit-enummixed -q nfgs/game57.nfg
gambit-enummixed -q nfgs/game58.nfg
gambit-enummixed -q nfgs/game59.nfg
gambit-enummixed -q nfgs/game60.nfg
gambit-enummixed -q nfgs/game61.nfg
gambit-enummixed -q nfgs/game62.nfg
gambit-enummixed -q nfgs/game63.nfg
gambit-enummixed -q nfgs/game64.nfg
gambit-enummixed -q nfgs/game65.nfg
gambit-enummixed -q nfgs/game66.nfg
gambit-enummixed -q nfgs/game67.nfg
gambit-enummixed -q nfgs/game68.nfg
gambit-enummixed -q nfgs/game69.nfg
gambit-enummixed -q nfgs/game70.nfg
gambit-enummixed -q nfgs/game71.nfg
gambit-enummixed -q nfgs/game72.nfg
gambit-enummixed -q nfgs/game73.nfg
gambit-enummixed -q nfgs/game74.nfg
gambit-enummixed -q nfgs/game75.nfg
gambit-enummixed -q nfgs/game76.nfg
gambit-enummixed -q nfgs/game77.nfg
gambit-enummixed -q nfgs/game78.nfg
gambit-enummixed -q nfgs/game79.nfg
gambit-enummixed -q nfgs/game80.nfg
gambit-enummixed -q nfgs/game81.nfg
gambit-enummixed -q nfgs/game82.nfg
gambit-enummixed -q nfgs/game83.nfg
gambit-enummixed -q nfgs/game84.nfg
gambit-enummixed -q nfgs/game85.nfg
gambit-enummixed -q nfgs/game86.nfg
gambit-enummixed -q nfgs/game87.nfg
gambit-enummixed -q nfgs/game88.nfg
gambit-enummixed -q nfgs/game89.nfg
gambit-enummixed -q nfgs/game90.nfg
gambit-enummixed -q nfgs/game91.nfg
gambit-enummixed -q nfgs/game92.nfg
gambit-enummixed -q nfgs/game93.nfg
gambit-enummixed -q nfgs/game94.nfg
gambit-enummixed -q nfgs/game95.nfg
gambit-enummixed -q nfgs/game96.nfg
gambit-enummixed -q nfgs/game97.nfg
gambit-enummixed -q nfgs/game98.nfg
gambit-enummixed -q nfgs/game99.nfg
cmd /k